# Generated by Django 3.2.10 on 2022-01-25 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ipost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=50)),
                ('can_comment', models.BooleanField(default=True)),
                ('tags', models.CharField(max_length=50)),
                ('image', models.ImageField(max_length=50, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='InstagramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('E_mail', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=200)),
                ('likedpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Likedby', to='API.ipost')),
            ],
        ),
    ]
